import { Language } from "./types";

export const CHUNK_SIZE = 300000; // ~75-80k tokens
export const MAX_CONCURRENT_REQUESTS = 1;
export const GEMINI_MODEL = 'gemini-3-pro-preview';

// UI Dictionary
export const UI_TEXT: Record<Language, any> = {
  EN: {
    title: "AI Book Summarizer",
    subtitle: "Deep knowledge extraction using Gemini 3",
    loginTitle: "AI Book Summarizer",
    loginSubtitle: "This app runs entirely in your browser. Your key is stored locally.",
    inputPlaceholder: "Paste your AI Studio API Key...",
    loginButton: "Enter",
    noKey: "No key?",
    getKeyLink: "Get a free key from Google AI Studio",
    logout: "Exit / Change Key",
    selectFile: "Select Book (PDF, EPUB, FB2)",
    changeFile: "Select Different Book",
    startAnalysis: "Start Analysis",
    logs: "Process Log",
    timeElapsed: "Elapsed",
    timeRem: "Est. Left",
    summaryTitle: "Summary",
    generatedBy: "Generated by AI Book Summarizer",
    download: "Download .md",
    copy: "Copy",
    copySuccess: "Copied to clipboard",
    fileParsed: "File parsed in",
    chars: "chars",
    chunking: "Splitting text",
    step1: "Phase 1: Extraction",
    step2: "Phase 2: Consolidation",
    step3: "Phase 3: Polishing",
    error: "Error",
    criticalError: "Critical Error",
    tokenUsage: "Session Token Usage",
    checkQuota: "Check Google Quota"
  },
  RU: {
    title: "AI Book Summarizer",
    subtitle: "Глубокий анализ книг с помощью Gemini 3",
    loginTitle: "AI Book Summarizer",
    loginSubtitle: "Приложение работает в браузере. Ваш ключ хранится локально.",
    inputPlaceholder: "Вставьте AI Studio API Key...",
    loginButton: "Войти",
    noKey: "Нет ключа?",
    getKeyLink: "Получить бесплатно в Google AI Studio",
    logout: "Выход / Сменить ключ",
    selectFile: "Выберите книгу (PDF, EPUB, FB2)",
    changeFile: "Выбрать другую книгу",
    startAnalysis: "Начать анализ",
    logs: "Лог процесса",
    timeElapsed: "Прошло",
    timeRem: "Осталось",
    summaryTitle: "Резюме",
    generatedBy: "Сгенерировано AI Book Summarizer",
    download: "Скачать .md",
    copy: "Копировать",
    copySuccess: "Скопировано в буфер",
    fileParsed: "Файл прочитан за",
    chars: "симв.",
    chunking: "Разбиение текста",
    step1: "Этап 1: Извлечение",
    step2: "Этап 2: Консолидация",
    step3: "Этап 3: Шлифовка",
    error: "Ошибка",
    criticalError: "Критическая ошибка",
    tokenUsage: "Токенов за сессию",
    checkQuota: "Проверить квоты Google"
  },
  ES: {
    title: "Resumidor de Libros IA",
    subtitle: "Extracción profunda de conocimiento usando Gemini 3",
    loginTitle: "Resumidor de Libros IA",
    loginSubtitle: "Esta aplicación se ejecuta en tu navegador. Tu clave se guarda localmente.",
    inputPlaceholder: "Pega tu clave API de AI Studio...",
    loginButton: "Entrar",
    noKey: "¿Sin clave?",
    getKeyLink: "Obtén una clave gratis en Google AI Studio",
    logout: "Salir",
    selectFile: "Seleccionar Libro (PDF, EPUB, FB2)",
    changeFile: "Seleccionar otro libro",
    startAnalysis: "Iniciar Análisis",
    logs: "Registro del Proceso",
    timeElapsed: "Transcurrido",
    timeRem: "Restante",
    summaryTitle: "Resumen",
    generatedBy: "Generado por AI Book Summarizer",
    download: "Descargar .md",
    copy: "Copiar",
    copySuccess: "Copiado",
    fileParsed: "Archivo analizado en",
    chars: "caracteres",
    chunking: "Dividiendo texto",
    step1: "Fase 1: Extracción",
    step2: "Fase 2: Consolidación",
    step3: "Fase 3: Pulido",
    error: "Error",
    criticalError: "Error Crítico",
    tokenUsage: "Uso de Tokens",
    checkQuota: "Verificar Cuota"
  },
  DE: {
    title: "AI Buch-Zusammenfasser",
    subtitle: "Tiefe Wissensextraktion mit Gemini 3",
    loginTitle: "AI Buch-Zusammenfasser",
    loginSubtitle: "Diese App läuft lokal. Ihr Schlüssel wird sicher gespeichert.",
    inputPlaceholder: "AI Studio API Key einfügen...",
    loginButton: "Eintreten",
    noKey: "Kein Schlüssel?",
    getKeyLink: "Kostenlosen Schlüssel erhalten",
    logout: "Ausgang",
    selectFile: "Buch auswählen (PDF, EPUB, FB2)",
    changeFile: "Anderes Buch wählen",
    startAnalysis: "Analyse starten",
    logs: "Prozessprotokoll",
    timeElapsed: "Vergangen",
    timeRem: "Verbleibend",
    summaryTitle: "Zusammenfassung",
    generatedBy: "Erstellt mit AI Book Summarizer",
    download: "Download .md",
    copy: "Kopieren",
    copySuccess: "Kopiert",
    fileParsed: "Datei analysiert in",
    chars: "Zeichen",
    chunking: "Textaufteilung",
    step1: "Phase 1: Extraktion",
    step2: "Phase 2: Konsolidierung",
    step3: "Phase 3: Polieren",
    error: "Fehler",
    criticalError: "Kritischer Fehler",
    tokenUsage: "Token-Verbrauch",
    checkQuota: "Quote prüfen"
  },
  FR: {
    title: "Résumeur de Livres IA",
    subtitle: "Extraction de connaissances approfondie avec Gemini 3",
    loginTitle: "Résumeur de Livres IA",
    loginSubtitle: "Cette application fonctionne dans votre navigateur. Votre clé est stockée localement.",
    inputPlaceholder: "Collez votre clé API AI Studio...",
    loginButton: "Entrer",
    noKey: "Pas de clé ?",
    getKeyLink: "Obtenir une clé gratuite",
    logout: "Sortie",
    selectFile: "Sélectionner un livre (PDF, EPUB, FB2)",
    changeFile: "Choisir un autre livre",
    startAnalysis: "Lancer l'analyse",
    logs: "Journal du processus",
    timeElapsed: "Écoulé",
    timeRem: "Restant",
    summaryTitle: "Résumé",
    generatedBy: "Généré par AI Book Summarizer",
    download: "Télécharger .md",
    copy: "Copier",
    copySuccess: "Copié",
    fileParsed: "Fichier analysé en",
    chars: "caractères",
    chunking: "Découpage du texte",
    step1: "Phase 1 : Extraction",
    step2: "Phase 2 : Consolidation",
    step3: "Phase 3 : Peaufinage",
    error: "Erreur",
    criticalError: "Erreur Critique",
    tokenUsage: "Usage des jetons",
    checkQuota: "Vérifier quota"
  }
};

// Prompts Generation Function
export const getPrompts = (lang: Language) => {
  const langNameMap = {
    EN: "ENGLISH",
    RU: "RUSSIAN (CYRILLIC)",
    ES: "SPANISH",
    DE: "GERMAN",
    FR: "FRENCH"
  };

  const targetLang = langNameMap[lang];

  return {
    systemInstruction: `You are a professional book editor and summarizer. Your output language must be STRICTLY ${targetLang}. Never use other languages unless explicitly asked to translate.`,
    
    extract: `
      Extract and synthesize the most valuable, important, and practically applicable information from the provided text.
      Completely exclude theoretical "fluff", historical digressions, anecdotes, and any other non-essential details.
      Form a structured summary that allows understanding the essence without reading the whole text.
      
      If the text is cut off (as it is a chunk of a larger book), do not invent an ending, just process what is there.
      Structure the answer using headers.
      
      OUTPUT LANGUAGE: ${targetLang}.
      
      Are you sure? Did you miss anything? Double check.
    `,
    
    consolidate: `
      The document contains several summaries of sequential parts of a single book.
      Your task is to compile them into a single, exhaustive summary without losing useful information.
      If using headers, do not use headers larger than Level 3 (###). Use ####, #####, ######.
      Merge repeating themes, create a smooth narrative flow.
      
      OUTPUT LANGUAGE: ${targetLang}.
    `,
    
    polish: `
      Structure the provided text for a final note in Obsidian.
      Use headers H4 - H6 for hierarchy.
      Use nested lists for details.
      You are PROHIBITED from using *bold* and **italics**. All text must be regular weight.
      Ensure logic and structure. It is important not to lose information but to present it as concisely and usefully as possible.
      
      Output format: Markdown.
      OUTPUT LANGUAGE: ${targetLang}.
    `
  };
};