import { Language } from "./types";

// Chunk size updated to 100,000 as requested for broader context per chunk
export const CHUNK_SIZE = 100000; 
export const MAX_CONCURRENT_REQUESTS = 1;
export const GEMINI_MODEL = 'gemini-3-pro-preview';

// UI Dictionary
export const UI_TEXT: Record<Language, any> = {
  EN: {
    title: "AI Book Summarizer",
    subtitle: "Deep knowledge extraction",
    selectFile: "Select Book (ZIP, PDF, FB2, TXT, MD)",
    changeFile: "Select Different Book",
    startAnalysis: "Start Deep Analysis",
    logs: "Process Log",
    timeElapsed: "Elapsed",
    timeRem: "Est. Left",
    summaryTitle: "Summary",
    generatedBy: "Generated by AI Book Summarizer",
    download: "Download .md",
    copy: "Copy",
    copySuccess: "Copied to clipboard",
    fileParsed: "File parsed in",
    chars: "chars",
    chunking: "Splitting text",
    step1: "Phase 1: Deep Extraction",
    step2: "Phase 2: Consolidation",
    step3: "Phase 3: Polishing & Formatting",
    error: "Error",
    criticalError: "Critical Error",
    tokenUsage: "Session Token Usage",
    checkQuota: "Check Google Quota",
    tabAnalyze: "Analyze",
    tabHistory: "History",
    historyEmpty: "No summaries found yet.",
    import: "Import JSON",
    export: "Export JSON",
    delete: "Delete",
    view: "View",
    restoreMsg: "History imported successfully",
    statusThinking: "Analyzing content...",
    statusReading: "Reading document...",
    statusWriting: "Structuring final notes..."
  },
  RU: {
    title: "AI Book Summarizer",
    subtitle: "Глубокий анализ книг",
    selectFile: "Выберите книгу (ZIP, PDF, FB2, TXT, MD)",
    changeFile: "Выбрать другую книгу",
    startAnalysis: "Начать глубокий анализ",
    logs: "Лог процесса",
    timeElapsed: "В работе",
    timeRem: "Осталось",
    summaryTitle: "Резюме",
    generatedBy: "Сгенерировано AI Book Summarizer",
    download: "Скачать .md",
    copy: "Копировать",
    copySuccess: "Скопировано в буфер",
    fileParsed: "Файл прочитан за",
    chars: "симв.",
    chunking: "Разбиение текста",
    step1: "Этап 1: Глубокое извлечение",
    step2: "Этап 2: Сборка (Консолидация)",
    step3: "Этап 3: Шлифовка и структура",
    error: "Ошибка",
    criticalError: "Критическая ошибка",
    tokenUsage: "Токенов за сессию",
    checkQuota: "Проверить квоты Google",
    tabAnalyze: "Анализ",
    tabHistory: "История",
    historyEmpty: "История пуста.",
    import: "Импорт JSON",
    export: "Экспорт JSON",
    delete: "Удалить",
    view: "Открыть",
    restoreMsg: "История успешно восстановлена",
    statusThinking: "Анализ содержимого...",
    statusReading: "Чтение файла...",
    statusWriting: "Формирование заметки..."
  },
  ES: {
    title: "Resumidor de Libros IA",
    subtitle: "Extracción profunda",
    selectFile: "Seleccionar Libro (ZIP, PDF, FB2, TXT, MD)",
    changeFile: "Seleccionar otro libro",
    startAnalysis: "Iniciar Análisis Profundo",
    logs: "Registro del Proceso",
    timeElapsed: "Transcurrido",
    timeRem: "Restante",
    summaryTitle: "Resumen",
    generatedBy: "Generado por AI Book Summarizer",
    download: "Descargar .md",
    copy: "Copiar",
    copySuccess: "Copiado",
    fileParsed: "Archivo analizado en",
    chars: "caracteres",
    chunking: "Dividiendo texto",
    step1: "Fase 1: Extracción Profunda",
    step2: "Fase 2: Consolidación",
    step3: "Fase 3: Pulido y Estructura",
    error: "Error",
    criticalError: "Error Crítico",
    tokenUsage: "Uso de Tokens",
    checkQuota: "Verificar Cuota",
    tabAnalyze: "Analizar",
    tabHistory: "Historial",
    historyEmpty: "No hay historial.",
    import: "Importar JSON",
    export: "Exportar JSON",
    delete: "Borrar",
    view: "Ver",
    restoreMsg: "Historial restaurado",
    statusThinking: "Analizando contenido...",
    statusReading: "Leyendo...",
    statusWriting: "Estructurando..."
  },
  DE: {
    title: "AI Buch-Zusammenfasser",
    subtitle: "Tiefe Extraktion",
    selectFile: "Buch auswählen (ZIP, PDF, FB2, TXT, MD)",
    changeFile: "Anderes Buch wählen",
    startAnalysis: "Tiefenanalyse starten",
    logs: "Prozessprotokoll",
    timeElapsed: "Vergangen",
    timeRem: "Verbleibend",
    summaryTitle: "Zusammenfassung",
    generatedBy: "Erstellt mit AI Book Summarizer",
    download: "Download .md",
    copy: "Kopieren",
    copySuccess: "Kopiert",
    fileParsed: "Datei analysiert in",
    chars: "Zeichen",
    chunking: "Textaufteilung",
    step1: "Phase 1: Tiefe Extraktion",
    step2: "Phase 2: Konsolidierung",
    step3: "Phase 3: Strukturierung",
    error: "Fehler",
    criticalError: "Kritischer Fehler",
    tokenUsage: "Token-Verbrauch",
    checkQuota: "Quote prüfen",
    tabAnalyze: "Analysieren",
    tabHistory: "Verlauf",
    historyEmpty: "Kein Verlauf.",
    import: "JSON Importieren",
    export: "JSON Exportieren",
    delete: "Löschen",
    view: "Ansehen",
    restoreMsg: "Verlauf wiederhergestellt",
    statusThinking: "Inhaltsanalyse...",
    statusReading: "Lese...",
    statusWriting: "Strukturierung..."
  },
  FR: {
    title: "Résumeur de Livres IA",
    subtitle: "Extraction approfondie",
    selectFile: "Sélectionner un livre (ZIP, PDF, FB2, TXT, MD)",
    changeFile: "Choisir un autre livre",
    startAnalysis: "Analyse approfondie",
    logs: "Journal",
    timeElapsed: "Écoulé",
    timeRem: "Restant",
    summaryTitle: "Résumé",
    generatedBy: "Généré par AI Book Summarizer",
    download: "Télécharger .md",
    copy: "Copier",
    copySuccess: "Copié",
    fileParsed: "Fichier analysé en",
    chars: "caractères",
    chunking: "Découpage",
    step1: "Phase 1 : Extraction approfondie",
    step2: "Phase 2 : Consolidation",
    step3: "Phase 3 : Structure finale",
    error: "Error",
    criticalError: "Erreur Critique",
    tokenUsage: "Usage des jetons",
    checkQuota: "Vérifier quota",
    tabAnalyze: "Analyser",
    tabHistory: "Historique",
    historyEmpty: "Historique vide.",
    import: "Importer JSON",
    export: "Exporter JSON",
    delete: "Supprimer",
    view: "Voir",
    restoreMsg: "Historique restauré",
    statusThinking: "Analyse du contenu...",
    statusReading: "Lecture...",
    statusWriting: "Rédaction..."
  }
};

export const getPrompts = (lang: Language) => {
  const langNameMap = {
    EN: "ENGLISH",
    RU: "RUSSIAN",
    ES: "SPANISH",
    DE: "GERMAN",
    FR: "FRENCH"
  };

  const targetLang = langNameMap[lang];
  
  const extractPrompt = lang === 'RU' 
    ? `Извлеки и синтезируй самую ценную, важную и практически применимую информацию из всех предоставленных источников. Полностью исключи теоретическую "воду", исторические отступления, анекдоты и любые другие неessentialные детали. Сформируй структурированное резюме, которое позволит понять суть всех источников без необходимости читать их целиком.
    
    Точно всё? Ты ничего не упустил? Перепроверь.
    Язык вывода: РУССКИЙ.`
    : `Extract and synthesize the most valuable, important, and practically applicable information from the provided text. Completely exclude theoretical "fluff", historical digressions, anecdotes, and any other non-essential details. Form a structured summary that allows understanding the essence of all sources without reading them entirely.
    
    Make sure you haven't missed anything important. Double check.
    OUTPUT LANGUAGE: ${targetLang}.`;

  const consolidatePrompt = lang === 'RU'
    ? `В документе представлено несколько пересказов одного и того же источника (последовательных частей книги). Твоя задача скомпилировать из них единый, исчерпывающий пересказ, без потери полезной информации. Если используешь заголовки, то не используй заголовки старше 3 (###) включительно, используй 4, 5, 6. Изменения следует вносить в сам документ.
    
    Язык вывода: РУССКИЙ.`
    : `The document contains several summaries of sequential parts of a single book. Your task is to compile them into a single, exhaustive summary without losing useful information. If using headers, do not use headers larger than Level 3 (###). Use ####, #####, ######. Merge into a cohesive text.
    
    OUTPUT LANGUAGE: ${targetLang}.`;

  const polishPrompt = lang === 'RU'
    ? `Структурируй текст ниже. Используй, если необходимо, заголовки H4 - H6, вложенные списки, нумерованные списки и т.д. 
    
    ТЕБЕ ЗАПРЕЩЕНО ИСПОЛЬЗОВАНИЕ **ЖИРНОГО** (bold) И *КУРСИВА* (italics). Не используй символы ** или * для выделения текста. ВЕСЬ ТЕКСТ ДОЛЖЕН БЫТЬ ОБЫЧНЫМ (Regular weight).
    
    Важно не потерять информацию, а структурировать её.
    Язык вывода: РУССКИЙ.`
    : `Structure the text below. Use headers H4 - H6, nested lists, numbered lists, etc.
    
    YOU ARE PROHIBITED FROM USING **BOLD** OR *ITALICS*. Do not use ** or * markers.
    
    It is important not to lose information.
    OUTPUT LANGUAGE: ${targetLang}.`;

  return {
    systemInstruction: `You are a strict technical editor. Your output language is ${targetLang}. You follow instructions literally. No Markdown bold or italics allowed.`,
    extract: extractPrompt,
    consolidate: consolidatePrompt,
    polish: polishPrompt
  };
};